#Requires -Version 5.1
<#
.SYNOPSIS
    Extracts a small, self-contained test slice from a real Second Life /
    Firestorm texture cache into tests/data/.

.DESCRIPTION
    The fixtures are tiny (a few tens of kilobytes) and are committed to the
    repository so that the unit tests do not depend on a multi-gigabyte cache.
    Every fixture is a verbatim copy of real bytes; the only modification is
    applied to entries_mini.bin, whose mEntries field is patched so that the
    file becomes self-consistent (see the manifest).

    Reference records:
        0    - free slot (mBodySize = 0) whose .texture file still exists
        100  - "class B": imageSize == bodySize + 601, cached data is truncated
        394  - "class A": imageSize == bodySize + 600, complete codestream

.PARAMETER CacheDir
    Directory that contains texture.entries / texture.cache / 0..f shards.

.PARAMETER OutDir
    Destination directory (defaults to <repo>/tests/data).
#>
[CmdletBinding()]
param(
    [string]$CacheDir = 'D:\FS Cache\texturecache',
    [string]$OutDir = (Join-Path (Split-Path -Parent $PSScriptRoot) 'tests\data')
)

$ErrorActionPreference = 'Stop'

$entriesPath = Join-Path $CacheDir 'texture.entries'
$cachePath = Join-Path $CacheDir 'texture.cache'
# The slice must contain every reference index (0, 100, 394), so take the
# contiguous range 0..394.
$miniCount = 395
$refIndices = 0, 100, 394

function Format-UUID([byte[]]$bytes) {
    $hex = -join ($bytes | ForEach-Object { $_.ToString('x2') })
    return $hex.Substring(0, 8) + '-' + $hex.Substring(8, 4) + '-' + $hex.Substring(12, 4) +
           '-' + $hex.Substring(16, 4) + '-' + $hex.Substring(20, 12)
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

$entries = [IO.File]::ReadAllBytes($entriesPath)
$cache = [IO.File]::ReadAllBytes($cachePath)

if ($entries.Length -lt 44) { throw "texture.entries is too small: $($entries.Length) bytes" }

# ---------------------------------------------------------------------------
# 1. The real 44 byte header, verbatim (mEntries == 196700).
# ---------------------------------------------------------------------------
$header = New-Object byte[] 44
[Array]::Copy($entries, 0, $header, 0, 44)
[IO.File]::WriteAllBytes((Join-Path $OutDir 'entries_header_real.bin'), $header)

# ---------------------------------------------------------------------------
# 2. Mini entries file: real header with mEntries patched to 128 + 128 real
#    records -> a valid, self-consistent file used by parser tests.
# ---------------------------------------------------------------------------
$mini = New-Object byte[] (44 + $miniCount * 28)
[Array]::Copy($entries, 0, $mini, 0, $mini.Length)
[BitConverter]::GetBytes([int]$miniCount).CopyTo($mini, 40)
[IO.File]::WriteAllBytes((Join-Path $OutDir 'entries_mini.bin'), $mini)

# ---------------------------------------------------------------------------
# 3. Truncated file: real header (mEntries == 196700) + only 128 records.
#    Used to test that the parser rejects a file whose size does not match.
# ---------------------------------------------------------------------------
$truncated = New-Object byte[] (44 + $miniCount * 28)
[Array]::Copy($entries, 0, $truncated, 0, $truncated.Length)
[IO.File]::WriteAllBytes((Join-Path $OutDir 'entries_truncated.bin'), $truncated)

# ---------------------------------------------------------------------------
# 4. Header cache blocks + body files for the reference records.
# ---------------------------------------------------------------------------
$manifest = New-Object System.Collections.Generic.List[string]
$manifest.Add('# Generated by tools/make_test_slice.ps1 - do not edit by hand.')
$manifest.Add("# source: $CacheDir")
$manifest.Add("# entries file: $($entries.Length) bytes, cache file: $($cache.Length) bytes")
$manifest.Add('')

foreach ($i in $refIndices) {
    $offset = 44 + $i * 28
    $uuidBytes = New-Object byte[] 16
    [Array]::Copy($entries, $offset, $uuidBytes, 0, 16)
    $uuid = Format-UUID $uuidBytes
    $imageSize = [BitConverter]::ToInt32($entries, $offset + 16)
    $bodySize = [BitConverter]::ToInt32($entries, $offset + 20)
    $timestamp = [BitConverter]::ToUInt32($entries, $offset + 24)

    $block = New-Object byte[] 600
    [Array]::Copy($cache, $i * 600, $block, 0, 600)
    [IO.File]::WriteAllBytes((Join-Path $OutDir "block_$i.bin"), $block)

    $bodySrc = Join-Path $CacheDir "$($uuid.Substring(0, 1))\$uuid.texture"
    $bodyDst = Join-Path $OutDir "body_$i.texture"
    if (Test-Path $bodySrc) {
        Copy-Item $bodySrc $bodyDst -Force
        $bodyFileSize = (Get-Item $bodyDst).Length
    } else {
        $bodyDst = '(missing)'
        $bodyFileSize = 0
    }

    $manifest.Add("[$i]")
    $manifest.Add("uuid=$uuid")
    $manifest.Add("imageSize=$imageSize")
    $manifest.Add("bodySize=$bodySize")
    $manifest.Add("timestamp=$timestamp")
    $manifest.Add("bodyFileSizeOnDisk=$bodyFileSize")
    $manifest.Add("block=block_$i.bin")
    $manifest.Add("body=body_$i.texture")
    $manifest.Add('')
}

$manifest | Set-Content -Path (Join-Path $OutDir 'manifest.txt') -Encoding ASCII

Get-ChildItem $OutDir | Sort-Object Name | Format-Table Name, Length -AutoSize
Write-Host "Test slice written to $OutDir"
