#Requires -Version 5.1
<#
.SYNOPSIS
    Produces a reference pixel dump for one frozen record by decoding the
    assembled codestream with the standalone opj_decompress utility.

.DESCRIPTION
    The dump is written as an interleaved 8 bit raw image
    (<name>.rgba, componentCount bytes per pixel) plus a small key=value file
    (<name>.info) that records the dimensions and the tool that produced it.

    opj_decompress writes one PGX plane per component; this script validates
    the PGX headers and interleaves the planes so that the C++ tests can
    compare their own decoder output byte for byte against an independent
    implementation.

.PARAMETER DataDir
    Directory holding the frozen fixtures (block_<i>.bin, body_<i>.texture).

.PARAMETER RecordIndex
    Which frozen record to use (must have a block_<i>.bin and body_<i>.texture).

.PARAMETER OpjDecompress
    Path to opj_decompress.exe.
#>
[CmdletBinding()]
param(
    [string]$DataDir = (Join-Path (Split-Path -Parent $PSScriptRoot) 'tests\data'),
    [int]$RecordIndex = 394,
    [string]$OpjDecompress = 'C:\msys64\mingw64\bin\opj_decompress.exe'
)

$ErrorActionPreference = 'Stop'

$blockPath = Join-Path $DataDir "block_$RecordIndex.bin"
$bodyPath = Join-Path $DataDir "body_$RecordIndex.texture"
foreach ($p in $blockPath, $bodyPath, $OpjDecompress) {
    if (-not (Test-Path $p)) { throw "not found: $p" }
}

$work = Join-Path ([IO.Path]::GetTempPath()) "sltcd_ref_$RecordIndex"
if (Test-Path $work) { Remove-Item $work -Recurse -Force }
New-Item -ItemType Directory -Path $work | Out-Null

# 1. Assemble the codestream: 600 byte header block followed by the body file.
$block = [IO.File]::ReadAllBytes($blockPath)
$body = [IO.File]::ReadAllBytes($bodyPath)
$codestream = New-Object byte[] ($block.Length + $body.Length)
[Array]::Copy($block, 0, $codestream, 0, $block.Length)
[Array]::Copy($body, 0, $codestream, $block.Length, $body.Length)
$j2k = Join-Path $work 'codestream.j2k'
[IO.File]::WriteAllBytes($j2k, $codestream)

# 2. Decode to PGX planes with the reference implementation.
$pgx = Join-Path $work 'plane.pgx'
& $OpjDecompress -i $j2k -o $pgx 2>&1 | Select-String -Pattern 'ERROR' | ForEach-Object { throw "opj_decompress: $_" }

$planes = @(Get-ChildItem $work -Filter 'plane_*.pgx' | Sort-Object Name)
if ($planes.Count -eq 0) { throw 'opj_decompress produced no PGX planes' }

# 3. Parse the PGX headers: "PG <endianness> <sign> <precision> <width> <height>".
$parsed = @()
foreach ($plane in $planes) {
    $bytes = [IO.File]::ReadAllBytes($plane.FullName)
    $headerEnd = [Array]::IndexOf($bytes, [byte]0x0A)
    if ($headerEnd -lt 0) { throw "malformed PGX header in $($plane.Name)" }
    $header = [Text.Encoding]::ASCII.GetString($bytes, 0, $headerEnd)
    $fields = $header -split '\s+'
    if ($fields.Count -ne 6 -or $fields[0] -ne 'PG') { throw "unexpected PGX header: '$header'" }
    $parsed += [pscustomobject]@{
        Precision = [int]$fields[3]
        Width     = [int]$fields[4]
        Height    = [int]$fields[5]
        Data      = $bytes[($headerEnd + 1)..($bytes.Length - 1)]
    }
}

$width = $parsed[0].Width
$height = $parsed[0].Height
$components = $parsed.Count

foreach ($plane in $parsed) {
    if ($plane.Width -ne $width -or $plane.Height -ne $height) { throw 'planes disagree on the image size' }
    if ($plane.Precision -ne 8) { throw "only 8 bit references are supported, got $($plane.Precision)" }
}

# 4. Interleave into a single raw image.
$pixels = New-Object byte[] ($width * $height * $components)
for ($i = 0; $i -lt ($width * $height); $i++) {
    for ($c = 0; $c -lt $components; $c++) {
        $pixels[$i * $components + $c] = $parsed[$c].Data[$i]
    }
}

$name = "reference_$RecordIndex"
[IO.File]::WriteAllBytes((Join-Path $DataDir "$name.rgba"), $pixels)

@(
    "# Generated by tools/make_reference_pixels.ps1 - do not edit by hand."
    "record=$RecordIndex"
    "width=$width"
    "height=$height"
    "components=$components"
    "maxval=255"
    "codestreamBytes=$($codestream.Length)"
    "source=$OpjDecompress (PGX planes, interleaved into $name.rgba)"
) | Set-Content -Path (Join-Path $DataDir "$name.info") -Encoding ASCII

Remove-Item $work -Recurse -Force
Write-Host "$name.rgba: ${width}x${height}x$components, $($pixels.Length) bytes"
